
clear
close all
clc

set(groot,'defaultTextInterpreter','latex', ...
    'defaultAxesTickLabelInterpreter','latex', ...
    'defaultLegendInterpreter','latex', ...
    'defaultColorbarTickLabelInterpreter','latex')

run('../fmm3dbie-hirax-dev/matlab/startup.m')
addpath('src')

level_directory = 'data';
candidate_orders = (4:2:10).';
wall_display_scale = 30;

file_orders = zeros(0,1);
level_files = cell(0,1);
for order_id = 1:numel(candidate_orders)
    level_file = sprintf('%s/run_hirax_single_leaf_order%d.mat', ...
        level_directory,candidate_orders(order_id));
    if isfile(level_file)
        file_orders(end+1,1) = candidate_orders(order_id);
        level_files{end+1,1} = level_file;
    else
        fprintf('Order %d file is absent; ignoring it.\n', ...
            candidate_orders(order_id))
    end
end
completed_orders = zeros(0,1);
completed_files = cell(0,1);
completed_levels = cell(0,1);
for file_id = 1:numel(level_files)
    level_file = level_files{file_id};
    loaded = load(level_file,'level');
    level = loaded.level;
    is_complete = isfield(level,'finished') && level.finished && ...
        isfield(level,'evaluation_finished') && ...
        level.evaluation_finished && ...
        isfield(level,'escat');
    if is_complete
        completed_orders(end+1,1) = file_orders(file_id);
        completed_files{end+1,1} = level_file;
        completed_levels{end+1,1} = level;
    else
        fprintf('Ignoring incomplete level: %s\n',level_file)
    end
end

reference_order = completed_orders(end);
reference_file = completed_files{end};
reference_data = load(reference_file, ...
    'case_settings','level','S','densities','einc','hinc');
reference_level = reference_data.level;

%% Self-convergence

% Scattered electric field at all probe points.
reference_values = reference_level.escat(:);
reference_point_maximum = max(abs(reference_values));

% Surface-quadrature-weighted L2 norm of the three-component tangential
% surface current. The fourth density row is the scalar charge.
surface_weights = reference_data.S.wts(:).';
surface_current = reference_data.densities(1:3,:);
surface_current_point_energy = sum(abs(surface_current).^2,1);
reference_surface_current_norm = sqrt(real(sum( ...
    surface_weights.*surface_current_point_energy)));

comparison_orders = completed_orders(1:end-1);
number_of_comparisons = numel(comparison_orders);
maximum_absolute_difference = zeros(number_of_comparisons,1);
normalized_by_point_value = zeros(number_of_comparisons,1);
normalized_by_surface_current_norm = zeros(number_of_comparisons,1);

for order_id = 1:number_of_comparisons
    level = completed_levels{order_id};
    current_values = level.escat(:);
    maximum_absolute_difference(order_id) = max(abs( ...
        current_values-reference_values));
    normalized_by_point_value(order_id) = ...
        maximum_absolute_difference(order_id)/reference_point_maximum;
    normalized_by_surface_current_norm(order_id) = ...
        maximum_absolute_difference(order_id)/ ...
        reference_surface_current_norm;
end

digits_by_point_value = -log10(normalized_by_point_value);
digits_by_surface_current_norm = ...
    -log10(normalized_by_surface_current_norm);
digits_gained_per_surface_order = nan(number_of_comparisons,1);
for order_id = 1:number_of_comparisons-1
    order_step = comparison_orders(order_id+1)- ...
        comparison_orders(order_id);
    digits_gained_per_surface_order(order_id) = ...
        (digits_by_point_value(order_id+1)- ...
        digits_by_point_value(order_id))/order_step;
end

convergence_table = table(comparison_orders, ...
    maximum_absolute_difference,normalized_by_point_value, ...
    normalized_by_surface_current_norm,digits_by_point_value, ...
    digits_by_surface_current_norm,digits_gained_per_surface_order);

fprintf('Highest completed reference order: %d\n',reference_order)
fprintf('Maximum absolute reference-point value: %.16e\n', ...
    reference_point_maximum)
fprintf(['Surface-quadrature-weighted reference surface-current ' ...
    'L2 norm: %.16e\n'],reference_surface_current_norm)
disp(convergence_table)

convergence_figure = figure('Color','w','Position',[120 120 760 560]);
convergence_axes = axes(convergence_figure);
semilogy(convergence_axes,comparison_orders,normalized_by_point_value, ...
    'bo-','LineWidth',1.8,'MarkerSize',7,'MarkerFaceColor','b')
hold(convergence_axes,'on')
semilogy(convergence_axes,comparison_orders, ...
    normalized_by_surface_current_norm, ...
    'rs-','LineWidth',1.8,'MarkerSize',7,'MarkerFaceColor','w')
box(convergence_axes,'on')
xticks(convergence_axes,comparison_orders)
xlabel(convergence_axes,'surface order')
ylabel(convergence_axes,'normalized maximum reference-point error')

%% Shared geometry and display coordinates

% Keep the source in front while using a slightly oblique overhead view.
S = reference_data.S;
surface_center = sum(S.r.*surface_weights,2)/sum(surface_weights);
source_point = reference_level.source_point(:);
source_direction = source_point(1:2)-surface_center(1:2);
source_azimuth = atan2d(source_direction(2),source_direction(1));
source_view_azimuth = source_azimuth+65;
source_view_elevation = 32;

% Reconstruct the exact three-component NRCCIE right-hand side used by
% em_nrccie_pec_solver_guru:
%   rhs_t = n x Hinc - alpha n x n x Einc,
%   rhs_3 = n dot Einc.
alpha = reference_data.case_settings.alpha;

%% Incoming, scattered, and total field cross section

% Plot a vertical field cross section halfway from the dish center to the
% point source. The section normal is parallel to the center-source line,
% so the horizontal direction in the section is perpendicular to that
% line. For the vector Maxwell field, plot real(E dot n_section).
dish_radius = reference_data.case_settings.dish_radius;
thickness = reference_data.case_settings.thickness;
zk = reference_data.case_settings.zk;
eps_quad = reference_data.case_settings.eps_quad;
original_dish_radius = 69.25;
geometry_display_scale = original_dish_radius/dish_radius;
S_display = scale(S,geometry_display_scale);
source_point_display = geometry_display_scale*source_point;

section_fraction = 0.75;
section_horizontal_points = 181;
section_vertical_points = 161;
section_half_width = 1.05*dish_radius;
section_half_height = 0.8*dish_radius;

section_normal_xy = source_direction/norm(source_direction);
section_tangent_xy = [-section_normal_xy(2);section_normal_xy(1)];
section_center_xy = surface_center(1:2)+ ...
    section_fraction*source_direction;
section_u_values = linspace(-section_half_width,section_half_width, ...
    section_horizontal_points);
section_z_values = linspace(-section_half_height,section_half_height, ...
    section_vertical_points);
[section_u,section_z] = meshgrid(section_u_values,section_z_values);
section_x = section_center_xy(1)+section_tangent_xy(1)*section_u;
section_y = section_center_xy(2)+section_tangent_xy(2)*section_u;
section_x_display = geometry_display_scale*section_x;
section_y_display = geometry_display_scale*section_y;
section_z_display = geometry_display_scale*section_z;
section_border_u = section_half_width*[-1 1 1 -1 -1];
section_border_z = section_half_height*[-1 -1 1 1 -1];
section_border_x_display = geometry_display_scale*( ...
    section_center_xy(1)+section_tangent_xy(1)*section_border_u);
section_border_y_display = geometry_display_scale*( ...
    section_center_xy(2)+section_tangent_xy(2)*section_border_u);
section_border_z_display = geometry_display_scale*section_border_z;

outline_hull = convhull(S.r(1,:).',S.r(2,:).');
line_x = section_center_xy(1)+ ...
    section_tangent_xy(1)*section_u_values;
line_y = section_center_xy(2)+ ...
    section_tangent_xy(2)*section_u_values;
line_inside_dish = inpolygon(line_x,line_y, ...
    S.r(1,outline_hull),S.r(2,outline_hull));
inside_plate = repmat(line_inside_dish,section_vertical_points,1) & ...
    abs(section_z)<=thickness/2;
evaluate_section = ~inside_plate;

section_target_info = struct();
section_target_info.r = [section_x(evaluate_section).'; ...
    section_y(evaluate_section).';section_z(evaluate_section).'];
source_info = struct();
source_info.r = source_point;
source_info.edips = -reference_data.case_settings.p0;
[section_einc,~] = em3d.incoming_sources( ...
    zk,source_info,section_target_info,'electric dipole');

section_evaluator_options = struct();
section_evaluator_options.rep = 'nrccie';
[section_escat,~] = em3d.pec.eval( ...
    S,reference_data.densities,section_target_info,eps_quad,zk,alpha, ...
    section_evaluator_options);
section_etotal = section_einc+section_escat;

section_component_direction = [section_normal_xy;0];
section_component_values = complex(nan( ...
    section_vertical_points,section_horizontal_points,3));
section_valid_ids = find(evaluate_section);
section_plane_size = numel(evaluate_section);
section_component_values(section_valid_ids) = ...
    sum(section_component_direction.*section_einc,1);
section_component_values(section_valid_ids+section_plane_size) = ...
    sum(section_component_direction.*section_escat,1);
section_component_values(section_valid_ids+2*section_plane_size) = ...
    sum(section_component_direction.*section_etotal,1);
section_component_parts = cat(4,real(section_component_values), ...
    imag(section_component_values));

section_color_limit = max(abs(section_component_parts),[], ...
    'all','omitnan');

section_figure = figure('Color','w','Position',[50 50 1500 950], ...
    'Renderer','opengl','GraphicsSmoothing','on');
section_layout = tiledlayout(section_figure,2,3, ...
    'TileSpacing','compact','Padding','compact');
section_axes = gobjects(6,1);
for section_tile = 1:6
    field_id = mod(section_tile-1,3)+1;
    part_id = 1+(section_tile>3);
    section_plot_values = section_component_parts(:,:,field_id,part_id);
    section_plot_x = section_x_display;
    section_plot_y = section_y_display;
    section_plot_z = section_z_display;
    section_invalid = ~isfinite(section_plot_values);
    section_plot_x(section_invalid) = NaN;
    section_plot_y(section_invalid) = NaN;
    section_plot_z(section_invalid) = NaN;
    section_axes(section_tile) = nexttile(section_layout,section_tile);
    section_surface = surf(section_axes(section_tile), ...
        section_plot_x,section_plot_y,section_plot_z, ...
        section_plot_values, ...
        'FaceColor','interp','EdgeColor','none');
    hold(section_axes(section_tile),'on')
    plot3(section_axes(section_tile),section_border_x_display, ...
        section_border_y_display,section_border_z_display, ...
        'k-','LineWidth',1.4)
    axes(section_axes(section_tile))
    dish_handle = plot(S_display,zeros(S_display.npatches,1), ...
        'FaceColor',[0.05 0.36 0.20], ...
        'FaceAlpha',1,'EdgeColor','none','LineStyle','none');
    set(dish_handle,'FaceColor',[0.05 0.36 0.20], ...
        'FaceAlpha',1,'EdgeColor','none','LineStyle','none')
    plot3(section_axes(section_tile),source_point_display(1), ...
        source_point_display(2),source_point_display(3), ...
        'ro','MarkerFaceColor','r','MarkerSize',6)
    hold(section_axes(section_tile),'off')
    axis(section_axes(section_tile),'equal')
    axis(section_axes(section_tile),'tight')
    daspect(section_axes(section_tile),[1 1 1])
    view(section_axes(section_tile),source_azimuth+28,24)
    camproj(section_axes(section_tile),'orthographic')
    grid(section_axes(section_tile),'off')
    box(section_axes(section_tile),'on')
    clim(section_axes(section_tile),[-section_color_limit section_color_limit])
end
section_colormap_position = linspace(-1,1,512).';
section_colormap = [ ...
    min(1,1+section_colormap_position), ...
    1-abs(section_colormap_position), ...
    min(1,1-section_colormap_position)];
colormap(section_figure,section_colormap)
section_colorbar = colorbar(section_axes(end));
section_colorbar.Layout.Tile = 'east';

%% Source-side surface path data

% Sample the solved Cartesian surface current and charge along the
% source-side path and a second path roughly one eighth turn away.
number_of_core_triangles = ...
    reference_level.number_of_core_triangles_per_face;
number_of_outline_panels = reference_level.number_of_outline_panels;
number_of_wall_panels = ...
    reference_level.number_of_wall_profile_panels_per_half;

top_collar_patches = number_of_core_triangles+ ...
    (1:number_of_outline_panels);
upper_wall_start = top_collar_patches(end)+1;
upper_wall_end = upper_wall_start+ ...
    number_of_outline_panels*number_of_wall_panels-1;
lower_wall_start = upper_wall_end+1;
lower_wall_end = lower_wall_start+ ...
    number_of_outline_panels*number_of_wall_panels-1;
bottom_collar_patches = lower_wall_end+(1:number_of_outline_panels);

top_wall_join_uv = [zeros(1,number_of_outline_panels); ...
    -ones(1,number_of_outline_panels)];
top_wall_join_points = interpolate_data( ...
    S,S.r,top_collar_patches,top_wall_join_uv);
[~,source_side_panel] = min(vecnorm( ...
    top_wall_join_points(1:2,:)-source_point(1:2),2,1));
off_source_offset = round(number_of_outline_panels/8);
off_source_candidates = 1+mod( ...
    source_side_panel-1+[-off_source_offset off_source_offset], ...
    number_of_outline_panels);
[~,off_source_candidate_id] = min(vecnorm( ...
    top_wall_join_points(1:2,off_source_candidates)- ...
    source_point(1:2),2,1));
off_source_panel = off_source_candidates(off_source_candidate_id);

source_side_upper_wall = upper_wall_start+ ...
    (source_side_panel-1)*number_of_wall_panels+ ...
    (0:number_of_wall_panels-1);
source_side_lower_wall = lower_wall_start+ ...
    (source_side_panel-1)*number_of_wall_panels+ ...
    (0:number_of_wall_panels-1);
continuity_path_patches = [ ...
    top_collar_patches(source_side_panel), ...
    source_side_upper_wall,source_side_lower_wall, ...
    bottom_collar_patches(source_side_panel)];

off_source_upper_wall = upper_wall_start+ ...
    (off_source_panel-1)*number_of_wall_panels+ ...
    (0:number_of_wall_panels-1);
off_source_lower_wall = lower_wall_start+ ...
    (off_source_panel-1)*number_of_wall_panels+ ...
    (0:number_of_wall_panels-1);
off_source_path_patches = [ ...
    top_collar_patches(off_source_panel), ...
    off_source_upper_wall,off_source_lower_wall, ...
    bottom_collar_patches(off_source_panel)];

path_points_per_patch = 101;
path_local_coordinate = linspace(-1,1,path_points_per_patch);
number_of_path_patches = numel(continuity_path_patches);
continuity_patch_ids = repelem( ...
    continuity_path_patches,path_points_per_patch);
continuity_uv = zeros(2,numel(continuity_patch_ids));
for path_patch = 1:number_of_path_patches
    path_ids = (path_patch-1)*path_points_per_patch+ ...
        (1:path_points_per_patch);
    if path_patch==1
        continuity_uv(:,path_ids) = [ ...
            zeros(1,path_points_per_patch); ...
            fliplr(path_local_coordinate)];
    else
        continuity_uv(:,path_ids) = [ ...
            path_local_coordinate;zeros(1,path_points_per_patch)];
    end
end

continuity_points = interpolate_data( ...
    S,S.r,continuity_patch_ids,continuity_uv);
continuity_values = interpolate_data( ...
    S,reference_data.densities,continuity_patch_ids,continuity_uv);
continuity_arclength = geometry_display_scale*[0 cumsum(vecnorm( ...
    diff(continuity_points,1,2),2,1))];
continuity_landmark_indices = [1, ...
    path_points_per_patch*(1:number_of_path_patches-1), ...
    numel(continuity_arclength)];
continuity_landmarks = continuity_arclength(continuity_landmark_indices);
continuity_landmark_names = {'A','B','C','D'};

off_source_patch_ids = repelem( ...
    off_source_path_patches,path_points_per_patch);
off_source_points = interpolate_data( ...
    S,S.r,off_source_patch_ids,continuity_uv);
off_source_values = interpolate_data( ...
    S,reference_data.densities,off_source_patch_ids,continuity_uv);
off_source_arclength = geometry_display_scale*[0 cumsum(vecnorm( ...
    diff(off_source_points,1,2),2,1))];
off_source_landmarks = ...
    off_source_arclength(continuity_landmark_indices);
off_source_landmark_names = { ...
    '$A^{\prime}$','$B^{\prime}$','$C^{\prime}$','$D^{\prime}$'};

% Extend both paths through A and A' into the adjacent top-core triangle.
% This provides independent limits from the core and collar sides.
triangle_vertex_uv = [0 1 0;0 0 1];
triangle_edge_vertices = [1 2;2 3;3 1];
triangle_opposite_vertex = [3 1 2];
core_vertex_patch_ids = repelem( ...
    1:number_of_core_triangles,3);
core_vertex_uv = repmat( ...
    triangle_vertex_uv,1,number_of_core_triangles);
core_vertex_points = interpolate_data( ...
    S,S.r,core_vertex_patch_ids,core_vertex_uv);
core_vertex_points = reshape( ...
    core_vertex_points,3,3,number_of_core_triangles);

path_start_points = {continuity_points(:,1),off_source_points(:,1)};
core_extension_points = cell(1,2);
core_extension_values = cell(1,2);
core_extension_arclengths = cell(1,2);
for path_id = 1:2
    edge_midpoint_error = zeros(3,number_of_core_triangles);
    for edge_id = 1:3
        edge_vertices = triangle_edge_vertices(edge_id,:);
        edge_midpoints = 0.5*( ...
            core_vertex_points(:,edge_vertices(1),:)+ ...
            core_vertex_points(:,edge_vertices(2),:));
        edge_midpoints = reshape( ...
            edge_midpoints,3,number_of_core_triangles);
        edge_midpoint_error(edge_id,:) = vecnorm( ...
            edge_midpoints-path_start_points{path_id},2,1);
    end
    [~,closest_edge] = min(edge_midpoint_error(:));
    [edge_id,core_patch] = ind2sub( ...
        size(edge_midpoint_error),closest_edge);
    edge_vertices = triangle_edge_vertices(edge_id,:);
    edge_midpoint_uv = 0.5*( ...
        triangle_vertex_uv(:,edge_vertices(1))+ ...
        triangle_vertex_uv(:,edge_vertices(2)));
    opposite_uv = triangle_vertex_uv(:, ...
        triangle_opposite_vertex(edge_id));
    core_path_parameter = linspace(1,0,path_points_per_patch);
    core_path_uv = opposite_uv.*core_path_parameter+ ...
        edge_midpoint_uv.*(1-core_path_parameter);
    core_path_patch_ids = core_patch*ones(1,path_points_per_patch);
    core_extension_points{path_id} = interpolate_data( ...
        S,S.r,core_path_patch_ids,core_path_uv);
    core_extension_values{path_id} = interpolate_data( ...
        S,reference_data.densities,core_path_patch_ids,core_path_uv);
    core_arclength = geometry_display_scale*[0 cumsum(vecnorm( ...
        diff(core_extension_points{path_id},1,2),2,1))];
    core_extension_arclengths{path_id} = ...
        core_arclength-core_arclength(end);
end

%% Real current and charge near A--D and A'--D'

continuity_figure = figure('Color','w','Position',[100 100 900 700]);
continuity_layout = tiledlayout(continuity_figure,4,4, ...
    'TileSpacing','compact','Padding','compact');
continuity_path_arclengths = {continuity_arclength,off_source_arclength};
continuity_path_values = {continuity_values,off_source_values};
continuity_path_landmarks = {continuity_landmarks,off_source_landmarks};
continuity_path_landmark_names = { ...
    continuity_landmark_names,off_source_landmark_names};
continuity_path_core_arclengths = core_extension_arclengths;
continuity_path_core_values = core_extension_values;
continuity_axes = gobjects(4,4);
for path_id = 1:2
    path_arclength = continuity_path_arclengths{path_id};
    path_values = continuity_path_values{path_id};
    path_landmarks = continuity_path_landmarks{path_id};
    path_landmark_names = continuity_path_landmark_names{path_id};
    path_core_arclength = continuity_path_core_arclengths{path_id};
    path_core_values = continuity_path_core_values{path_id};
    current_row = 2*path_id-1;
    charge_row = current_row+1;

    for landmark_id = 1:4
        landmark_arclength = path_landmarks(landmark_id);
        local_arclength = path_arclength-landmark_arclength;
        if landmark_id==1
            local_half_width = 0.4*( ...
                path_landmarks(2)-path_landmarks(1));
            core_local_ids = path_core_arclength>=-local_half_width;
            collar_local_ids = local_arclength>=0 & ...
                local_arclength<=local_half_width;
            local_plot_arclength = [ ...
                path_core_arclength(core_local_ids), ...
                local_arclength(collar_local_ids)];
            local_plot_values = [ ...
                path_core_values(:,core_local_ids), ...
                path_values(:,collar_local_ids)];
            local_limits = [-local_half_width local_half_width];
        else
            local_half_width = 0.4*min( ...
                landmark_arclength-path_landmarks(landmark_id-1), ...
                path_landmarks(landmark_id+1)-landmark_arclength);
            local_ids = abs(local_arclength)<=local_half_width;
            local_plot_arclength = local_arclength(local_ids);
            local_plot_values = path_values(:,local_ids);
            local_limits = [-local_half_width local_half_width];
            boundary_id = landmark_id-1;
            left_id = boundary_id*path_points_per_patch;
            right_id = left_id+1;
        end

        tile_id = (current_row-1)*4+landmark_id;
        continuity_axes(current_row,landmark_id) = nexttile( ...
            continuity_layout,tile_id);
        current_lines = plot( ...
            continuity_axes(current_row,landmark_id), ...
            local_plot_arclength, ...
            real(local_plot_values(1:3,:)).','LineWidth',1.2);
        hold(continuity_axes(current_row,landmark_id),'on')
        xline(continuity_axes(current_row,landmark_id),0,':', ...
            'Color',[0.55 0.55 0.55],'HandleVisibility','off')
        for component_id = 1:3
            component_color = current_lines(component_id).Color;
            if landmark_id==1
                plot(continuity_axes(current_row,landmark_id),0, ...
                    real(path_core_values(component_id,end)),'o', ...
                    'Color',component_color,'MarkerFaceColor','w', ...
                    'MarkerSize',7,'LineWidth',1.2, ...
                    'HandleVisibility','off')
                plot(continuity_axes(current_row,landmark_id),0, ...
                    real(path_values(component_id,1)),'x', ...
                    'Color',component_color,'MarkerSize',8, ...
                    'LineWidth',1.4,'HandleVisibility','off')
            else
                plot(continuity_axes(current_row,landmark_id), ...
                    local_arclength(left_id), ...
                    real(path_values(component_id,left_id)),'o', ...
                    'Color',component_color,'MarkerFaceColor','w', ...
                    'MarkerSize',7,'LineWidth',1.2, ...
                    'HandleVisibility','off')
                plot(continuity_axes(current_row,landmark_id), ...
                    local_arclength(right_id), ...
                    real(path_values(component_id,right_id)),'x', ...
                    'Color',component_color,'MarkerSize',8, ...
                    'LineWidth',1.4,'HandleVisibility','off')
            end
        end
        hold(continuity_axes(current_row,landmark_id),'off')

        tile_id = (charge_row-1)*4+landmark_id;
        continuity_axes(charge_row,landmark_id) = nexttile( ...
            continuity_layout,tile_id);
        charge_line = plot(continuity_axes(charge_row,landmark_id), ...
            local_plot_arclength, ...
            real(local_plot_values(4,:)),'LineWidth',1.2);
        hold(continuity_axes(charge_row,landmark_id),'on')
        xline(continuity_axes(charge_row,landmark_id),0,':', ...
            'Color',[0.55 0.55 0.55],'HandleVisibility','off')
        if landmark_id==1
            plot(continuity_axes(charge_row,landmark_id),0, ...
                real(path_core_values(4,end)),'o', ...
                'Color',charge_line.Color,'MarkerFaceColor','w', ...
                'MarkerSize',7,'LineWidth',1.2, ...
                'HandleVisibility','off')
            plot(continuity_axes(charge_row,landmark_id),0, ...
                real(path_values(4,1)),'x', ...
                'Color',charge_line.Color,'MarkerSize',8, ...
                'LineWidth',1.4,'HandleVisibility','off')
        else
            plot(continuity_axes(charge_row,landmark_id), ...
                local_arclength(left_id),real(path_values(4,left_id)), ...
                'o','Color',charge_line.Color,'MarkerFaceColor','w', ...
                'MarkerSize',7,'LineWidth',1.2, ...
                'HandleVisibility','off')
            plot(continuity_axes(charge_row,landmark_id), ...
                local_arclength(right_id), ...
                real(path_values(4,right_id)),'x', ...
                'Color',charge_line.Color,'MarkerSize',8, ...
                'LineWidth',1.4,'HandleVisibility','off')
        end
        hold(continuity_axes(charge_row,landmark_id),'off')

        for row_id = [current_row charge_row]
            xlim(continuity_axes(row_id,landmark_id),local_limits)
            xticks(continuity_axes(row_id,landmark_id),0)
            xticklabels(continuity_axes(row_id,landmark_id), ...
                path_landmark_names(landmark_id))
            grid(continuity_axes(row_id,landmark_id),'off')
            box(continuity_axes(row_id,landmark_id),'on')
        end
    end
end

for path_id = 1:2
    current_row = 2*path_id-1;
    charge_row = current_row+1;
    current_legend = legend(continuity_axes(current_row,1), ...
        {'$J_x$','$J_y$','$J_z$'},'Location','best');
    current_legend.AutoUpdate = 'off';
    charge_legend = legend(continuity_axes(charge_row,1),'$\rho$', ...
        'Location','best');
    charge_legend.AutoUpdate = 'off';
    ylabel(continuity_axes(current_row,1),'real part')
    ylabel(continuity_axes(charge_row,1),'real part')
end

%% A--D and A'--D' surface paths on the mesh

continuity_geometry_figure = figure(continuity_figure.Number+1);
set(continuity_geometry_figure, ...
    'Color','w','Position',[100 100 900 700])
continuity_geometry_axes = axes(continuity_geometry_figure);
axes(continuity_geometry_axes)
continuity_display_surface = S_display;
continuity_core_display_width = 0.4*( ...
    continuity_landmarks(2)-continuity_landmarks(1));
continuity_core_display_ids = ...
    core_extension_arclengths{1}>=-continuity_core_display_width;
continuity_display_points = geometry_display_scale*[ ...
    core_extension_points{1}(:,continuity_core_display_ids), ...
    continuity_points(:,1:continuity_landmark_indices(4))];
off_source_core_display_width = 0.4*( ...
    off_source_landmarks(2)-off_source_landmarks(1));
off_source_core_display_ids = ...
    core_extension_arclengths{2}>=-off_source_core_display_width;
off_source_display_points = geometry_display_scale*[ ...
    core_extension_points{2}(:,off_source_core_display_ids), ...
    off_source_points(:,1:continuity_landmark_indices(4))];
continuity_display_source = source_point_display;
plot_surfer_patch_boundaries(continuity_geometry_axes, ...
    continuity_display_surface,[0.62 0.62 0.62],0.45, ...
    1:continuity_display_surface.npatches,[0;0;0],7);
hold(continuity_geometry_axes,'on')
plot3(continuity_geometry_axes,continuity_display_source(1), ...
    continuity_display_source(2),continuity_display_source(3), ...
    'ro','MarkerFaceColor','r','MarkerSize',6)
plot3(continuity_geometry_axes,continuity_display_points(1,:), ...
    continuity_display_points(2,:),continuity_display_points(3,:), ...
    'k-','LineWidth',2.0)
plot3(continuity_geometry_axes,off_source_display_points(1,:), ...
    off_source_display_points(2,:),off_source_display_points(3,:), ...
    'k--','LineWidth',2.0)
continuity_label_points = geometry_display_scale*continuity_points(:, ...
    continuity_landmark_indices(1:4));
off_source_label_points = geometry_display_scale*off_source_points(:, ...
    continuity_landmark_indices(1:4));
plot3(continuity_geometry_axes,continuity_label_points(1,:), ...
    continuity_label_points(2,:),continuity_label_points(3,:), ...
    'ko','MarkerFaceColor','w','MarkerSize',6,'LineWidth',1.2)
plot3(continuity_geometry_axes,off_source_label_points(1,:), ...
    off_source_label_points(2,:),off_source_label_points(3,:), ...
    'ko','MarkerFaceColor','w','MarkerSize',6,'LineWidth',1.2)
continuity_label_z_offset = ...
    0.003*original_dish_radius*[1 1 1 0];
continuity_label_xy_offset = zeros(2,4);
continuity_label_xy_offset(:,4) = ...
    -0.06*original_dish_radius*section_normal_xy;
for continuity_label = 1:4
    text(continuity_geometry_axes, ...
        continuity_label_points(1,continuity_label)+ ...
        continuity_label_xy_offset(1,continuity_label), ...
        continuity_label_points(2,continuity_label)+ ...
        continuity_label_xy_offset(2,continuity_label), ...
        continuity_label_points(3,continuity_label)+ ...
        continuity_label_z_offset(continuity_label), ...
        continuity_landmark_names{continuity_label}, ...
        'Color','k','FontWeight','bold','HorizontalAlignment','center', ...
        'Clipping','off')
end
off_source_label_z_offset = continuity_label_z_offset;
off_source_label_xy_offset = zeros(2,4);
off_source_outward_xy = top_wall_join_points(1:2,off_source_panel);
off_source_outward_xy = off_source_outward_xy/ ...
    norm(off_source_outward_xy);
off_source_label_xy_offset(:,4) = ...
    0.04*original_dish_radius*off_source_outward_xy;
for continuity_label = 1:4
    text(continuity_geometry_axes, ...
        off_source_label_points(1,continuity_label)+ ...
        off_source_label_xy_offset(1,continuity_label), ...
        off_source_label_points(2,continuity_label)+ ...
        off_source_label_xy_offset(2,continuity_label), ...
        off_source_label_points(3,continuity_label)+ ...
        off_source_label_z_offset(continuity_label), ...
        off_source_landmark_names{continuity_label}, ...
        'Color','k','FontWeight','bold','HorizontalAlignment','center', ...
        'Clipping','off')
end
hold(continuity_geometry_axes,'off')
view(continuity_geometry_axes,source_azimuth,0)
axis(continuity_geometry_axes,'equal')
axis(continuity_geometry_axes,'tight')
daspect(continuity_geometry_axes,[1 1 1/wall_display_scale])
grid(continuity_geometry_axes,'off')
box(continuity_geometry_axes,'on')
rotate3d(continuity_geometry_figure,'on')

%% NRCCIE right-hand-side surface error

surface_normal = S.n;
surface_ru = S.du;
surface_ru_norm = vecnorm(surface_ru,2,1);
surface_ru = surface_ru./surface_ru_norm;
surface_rv = cross(surface_normal,surface_ru,1);

normal_einc = sum(surface_normal.*reference_data.einc,1);
n_cross_hinc = cross(surface_normal,reference_data.hinc,1);
n_cross_n_cross_einc = surface_normal.*normal_einc-reference_data.einc;
combined_tangent_rhs = n_cross_hinc-alpha*n_cross_n_cross_einc;

nrccie_rhs = zeros(3,S.npts,'like',reference_data.einc);
nrccie_rhs(1,:) = sum(surface_ru.*combined_tangent_rhs,1);
nrccie_rhs(2,:) = sum(surface_rv.*combined_tangent_rhs,1);
nrccie_rhs(3,:) = normal_einc;

rhs_tangent_scale = max(abs(nrccie_rhs(1:2,:)),[],'all');
rhs_normal_scale = max(abs(nrccie_rhs(3,:)),[],'all');
rhs_tangent_tail = surf_fun_error( ...
    S,nrccie_rhs(1:2,:)/rhs_tangent_scale);
rhs_normal_tail = surf_fun_error(S,nrccie_rhs(3,:)/rhs_normal_scale);
rhs_patch_error = max([max(abs(rhs_tangent_tail),[],1); ...
    abs(rhs_normal_tail)],[],1).';
positive_rhs_error = rhs_patch_error(rhs_patch_error>0);
log_rhs_patch_error = log10(max( ...
    rhs_patch_error,min(positive_rhs_error)));

figure('Color','w','Position',[100 100 900 700])
plot(S_display,log_rhs_patch_error,'EdgeColor','none')
hold on
plot_surfer_patch_boundaries(gca,S_display,[0.15 0.15 0.15],0.18, ...
    1:S_display.npatches,[0;0;0],7);
plot3(source_point_display(1),source_point_display(2), ...
    source_point_display(3), ...
    'ro','MarkerFaceColor','r','MarkerSize',8)
hold off
view(source_view_azimuth,source_view_elevation)
axis tight
daspect([1 1 1/wall_display_scale])
grid off
box on
title(sprintf('NRCCIE RHS surface error, order %d',reference_order))
colorbar

%% Solved-density surface error

% FMM3DBIE density spectral-tail estimate on the highest completed order.
J = reference_data.densities(1:3,:);
rho = reference_data.densities(4,:);

current_scale = max(abs(J),[],'all');
charge_scale = max(abs(rho),[],'all');
current_tail_components = surf_fun_error(S,J./current_scale);
charge_tail = surf_fun_error(S,rho/charge_scale);

density_component_patch_error = [ ...
    abs(current_tail_components);abs(charge_tail(:).')];
positive_error = density_component_patch_error( ...
    density_component_patch_error>0);
log_density_component_patch_error = log10(max( ...
    density_component_patch_error,min(positive_error)));

density_error_color_limits = [ ...
    min(log_density_component_patch_error,[],'all'), ...
    max(log_density_component_patch_error,[],'all')];
density_error_figure = figure('Color','w','Position',[100 100 900 700]);
density_error_layout = tiledlayout(density_error_figure,2,2, ...
    'TileSpacing','compact','Padding','compact');
density_error_axes = gobjects(4,1);

for density_component = 1:4
    density_error_axes(density_component) = nexttile( ...
        density_error_layout,density_component);
    plot(S_display, ...
        log_density_component_patch_error(density_component,:).', ...
        'EdgeColor','none')
    hold(density_error_axes(density_component),'on')
    plot_surfer_patch_boundaries(density_error_axes(density_component), ...
        S_display, ...
        [0.15 0.15 0.15],0.18, ...
        1:S_display.npatches,[0;0;0],7);
    plot3(density_error_axes(density_component), ...
        source_point_display(1),source_point_display(2), ...
        source_point_display(3), ...
        'ro','MarkerFaceColor','r','MarkerSize',6)
    hold(density_error_axes(density_component),'off')
    view(density_error_axes(density_component), ...
        source_view_azimuth,source_view_elevation)
    axis(density_error_axes(density_component),'tight')
    daspect(density_error_axes(density_component), ...
        [1 1 1/wall_display_scale])
    grid(density_error_axes(density_component),'off')
    box(density_error_axes(density_component),'on')
    clim(density_error_axes(density_component),density_error_color_limits)
end

density_error_colorbar = colorbar(density_error_axes(end));
density_error_colorbar.Layout.Tile = 'east';

%% Real parts of the incident boundary data

% Real parts of all six boundary-field components. Each component gets its
% own figure and uses its own color scale.
boundary_data = [reference_data.einc;reference_data.hinc];
boundary_names = { ...
    '$\mathrm{Re}(E_x^{\mathrm{inc}})$', ...
    '$\mathrm{Re}(E_y^{\mathrm{inc}})$', ...
    '$\mathrm{Re}(E_z^{\mathrm{inc}})$', ...
    '$\mathrm{Re}(H_x^{\mathrm{inc}})$', ...
    '$\mathrm{Re}(H_y^{\mathrm{inc}})$', ...
    '$\mathrm{Re}(H_z^{\mathrm{inc}})$'};

for component = 1:size(boundary_data,1)
    plot_real_surface_component(S_display, ...
        real(boundary_data(component,:)), ...
        boundary_names{component},source_point_display,source_view_azimuth, ...
        source_view_elevation,wall_display_scale)
end

%% Real parts of the solved NRCCIE densities

% Real parts of all four NRCCIE densities: three Cartesian components of
% the tangential surface current and the scalar charge.
density_names = { ...
    '$\mathrm{Re}(J_x)$','$\mathrm{Re}(J_y)$', ...
    '$\mathrm{Re}(J_z)$','$\mathrm{Re}(\rho)$'};

for component = 1:size(reference_data.densities,1)
    plot_real_surface_component(S_display, ...
        real(reference_data.densities(component,:)), ...
        density_names{component},source_point_display,source_view_azimuth, ...
        source_view_elevation,wall_display_scale)
end


%% Local plotting function

function plot_real_surface_component(S,values,name,source_point, ...
        source_view_azimuth,source_view_elevation,wall_display_scale)
figure('Color','w','Position',[100 100 900 700])
plot(S,values,'EdgeColor','none')
hold on
plot3(source_point(1),source_point(2),source_point(3), ...
    'ro','MarkerFaceColor','r','MarkerSize',6)
hold off
view(source_view_azimuth,source_view_elevation)
axis tight
daspect([1 1 1/wall_display_scale])
grid off
box on
title(name)
colorbar
end
